// <auto-generated />
namespace Vetstore.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class gabiesgenial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gabiesgenial));
        
        string IMigrationMetadata.Id
        {
            get { return "201706032137475_gabiesgenial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
